import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { SlideMLGeneratedModule, JeyaSlidesGeneratedSharedModule } from './generated/module';
import { SlideMLValidator, registerValidationChecks } from './slide-ml-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SlideMLAddedServices = {
    validation: {
        SlideMLValidator: SlideMLValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SlideMLServices = LangiumServices & SlideMLAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SlideMLModule: Module<SlideMLServices, PartialLangiumServices & SlideMLAddedServices> = {
    validation: {
        SlideMLValidator: () => new SlideMLValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSlideMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SlideMl: SlideMLServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        JeyaSlidesGeneratedSharedModule
    );
    const SlideML = inject(
        createDefaultModule({ shared }),
        SlideMLGeneratedModule,
        SlideMLModule
    );
    shared.ServiceRegistry.register(SlideML);
    registerValidationChecks(SlideML);
    return { shared, SlideMl: SlideML };
}
